nome = str(input('Digite seu nome completo:')).strip()
nome1= nome.split()
print('ANALISANDO SEU NOME...')
print(f'Seu nome em MAIUSCULAS é {nome.upper()}')
print(f'Seu nome em minusculas é {nome.lower()}')
print(f'Seu nome tem ao todo {len(nome) - nome.count(" ")} letras')
print(f'Seu primeiro nome é {nome1 [0]} e o mesmo contem {len(nome1 [0])} letras ')
